version: "3.9"
services:
  frontend:
    build: /home/teo/hack/hack-dvloper-2023/frontend/chess-app
    ports:
      - "3000:3000"
  backend:
    build: /home/teo/hack/hack-dvloper-2023/backend/chess-app/src
    ports:
      - "5000:5000"
